# Generated by Django 6.0.5 on 2026-05-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_text', models.TextField()),
                ('placeholder_values', models.JSONField(default=dict)),
                ('image_url', models.URLField(max_length=1024)),
                ('thumb_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_content', models.TextField(unique=True)),
                ('placeholders', models.JSONField(default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='api.prompttemplate')),
                ('origin_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_templates', to='api.item')),
            ],
            options={
                'db_table': 'prompt_template',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.prompttemplate'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['copied_from'], name='prompt_temp_copied__b4b240_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['origin_item'], name='prompt_temp_origin__dae0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['is_locked'], name='prompt_temp_is_lock_0a7859_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['template'], name='item_templat_a9bc14_idx'),
        ),
    ]
