# Generated by Django 6.0.5 on 2026-05-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_user_prompttemplate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='next_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_templates', to='api.prompttemplate'),
        ),
    ]
