# Generated by Django 6.0.5 on 2026-05-14 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prompttemplate_next_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_public'], name='item_is_publ_e728ce_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['is_public'], name='prompt_temp_is_publ_1601a9_idx'),
        ),
    ]
